### PR TITLE
Revert "Prevent robot console from trimming log"

### PR DESCRIPTION
**Pull request by flemming-n-larsen**
Reverts robo-code/robocode#25

### CODE REVIEW

**Comment by flemming-n-larsen** [comment]
@bumfo: The pull-request is lacking the ConsoleTableModel class. Please add it to the PR. :-)

**Comment by bumfo** [comment]
Not sure how to append, but the content is short ;)
I'll try to find out how to append this file to the PR anyway. 

```
/**
 * Copyright (c) 2001-2019 Mathew A. Nelson and Robocode contributors
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * https://robocode.sourceforge.io/license/epl-v10.html
 */
package net.sf.robocode.ui.dialog;

import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import java.util.ArrayList;

/**
 * @author Xor
 */
public final class ConsoleTableModel extends AbstractTableModel implements TableModel {
	private final ArrayList<String> lines;

	public ConsoleTableModel(ArrayList<String> lines) {
		this.lines = lines;
	}

	@Override
	public int getRowCount() {
		return lines.size();
	}

	@Override
	public int getColumnCount() {
		return 1;
	}

	@Override
	public Class<?> getColumnClass(int i) {
		return String.class;
	}

	@Override
	public String getValueAt(int i, int i1) {
		if (0 <= i && i < getRowCount()) {
			return lines.get(i);
		}
		return "";
	}
}

```

**Comment by bumfo** [comment]
> @bumfo: The pull-request is lacking the ConsoleTableModel class. Please add it to the PR. :-)

I checked the PR again, it seems that in commit "use JTable for console to prevent trim", robocode.ui/src/main/java/net/sf/robocode/ui/dialog/ConsoleTableModel.java is there. What's wrong?

**Comment by flemming-n-larsen** [comment]
Weird. I will try to fix it. It might be the pico container (for dependency injection) that is broken or the merging that is given a problem?

**Pull request merged**
