### PR TITLE
Fix robot naming to be compatible with existing robots

### PR DESCRIPTION
**Pull request by agschultz**
This is a possible fix to make getName() compatible with the conventions expected by existing robots again, while also preserving the benefits of recent bug fixes.

Some principles followed in this code to avoid future recurrence of bugs similar to what have existed in the past:
- Never ever duplicate coming up with the suffix string, as that carries risk of becoming out of sync.
- Never ever duplicate how you derive the robot name, as that also carries risk of becoming out of sync.

The second point is why the name derived in Battle.createPeers() gets passed through to RobotStatics() despite the latter having sufficient information to easily derive the name on it's own. As a matter of principle, it seems like best practice to avoid unnecessarily duplicating the derivation of such an important value that needs to match between RobotPeer and TeamPeer, even if it's so simple to derive.

I will note, one underlying source of some of the awkwardness is that RobotStatics' constructor requires TeamPeer's memberNames already be finished, even before all of the RobotPeers are added to it. I had started considering one way of simplifying Battle.createPeers() to be 2 loops instead of 4, however that required removing the "memberNames" list from the TeamPeer constructor, and instead populate the list based on having TeamPeer.add() call RobotPeer.getName(). Unfortunately, this approach ran up against a problem with the RobotStatics() constructor requiring TeamPeer's "memberNames" list to already be fully populated. If populating the "teammates" array in RobotStatics could be deferred until after all RobotPeers are constructed and added to their corresponding TeamPeers, it would allow simplifying Battle.createPeers(), however it appears that would also require deferring IHostingRobotProxy.createRobotProxy to be after that rather than at RobotPeer constructor time... and that all started looking like surgery that would be going too deep for my tastes at this time :-)

As of this moment I've not added extra tests or extended existing tests for this, but may consider that.

### CODE REVIEW

**Review by jkflying — APPROVED** [review]
I like the numbering scheme this way (per bot name, no suffix if no duplicates), and this seems a more organized way of doing it as well. Don't know the ins and outs of the Battle.java enough to be a final review here though :wink:

**Comment by jkflying** [comment]
@flemming-n-larsen note the recent discussion here: https://robowiki.net/wiki/Talk:Tron#Tron_3.11_seems_broken_in_current_Robocode.2FJava_versions.3F_6747

**Comment by flemming-n-larsen** [comment]
The changes look good to me, and the solution is very clever and seems to be working close to how the names were like in the past. 👍 
I will try out the code locally, in order to approve the PR. :-)

**Review by flemming-n-larsen — APPROVED** [review]
I like your changes and cloned/branched the code locally to try it out. It works great and works pretty much as in the old days. Hopefully, fixes for old naming issues still work.

**Pull request merged**
