### PR TITLE
Fix codesize related logic

### PR DESCRIPTION
**Pull request by bumfo**
1. codesize calculation error is no longer silenced (and polluting roborumble) in roborumble@home. 
2. -cp options (codesize and bcel) in roborumble.sh etc. is fixed for roborumble to work properly. 
3. codesize is ensured when robot is downloaded to prevent polluting robot repository.

### CODE REVIEW

**Comment by bumfo** [comment]
This patch is not complete. Roborumble@Home can't load codesize utility even with this fix. 
Working on it...

**Comment by bumfo** [comment]
The patch is now tested and ready.

**Comment by jkflying** [comment]
@fnl will there be a release soon with this fix? Current 1.9.3.3 can't be used with the Rumble until this is in.

**Comment by flemming-n-larsen** [comment]
Hi Julian, :-)

Robocode 1.9.3.4 has already been released with a fix for Codesize:
https://sourceforge.net/projects/robocode/files/robocode/1.9.3.4/

In addition, I am working on version 1.9.3.5 containing more fixes. The final release should come at the end of February (I will be on holiday until that time). You can try out the 1.9.3.5 Beta here:
https://robocode.sourceforge.io/files/robocode-1.9.3.5-Beta-setup.jar.

If there are more issues, it would be great to include the fix for the final version of 1.9.3.5.

**Comment by bumfo** [comment]
@flemming-n-larsen is that possible to separate this fix with Kotlin fix etc.? Since 1.9.3.3 is fully tested with roborumble, and 1.9.3.4 + this fix is stable enough to be used directly by the roborumble community. 

If this fix is coupled with other fixes that touches robocode engine, it will be hard for the community to choose a version to use should there be any new problems. 

My suggestion is that we release 1.9.3.5 with this fix (and other small fixes if possible), and leave risky fixes (such as Kotlin support) to 1.9.3.6. This will at lease leave 19.3.5 a stable version.

**Comment by bumfo** [comment]
> @flemming-n-larsen is that possible to separate this fix with Kotlin fix etc.? Since 1.9.3.3 is fully tested with roborumble, and 1.9.3.4 + this fix is stable enough to be used directly by the roborumble community.

No need to worry. The kotlin fix won't change any behavior at all as long as a kotlin jar is not put into robocode/libs.

**Comment by flemming-n-larsen** [comment]
@bumfo & @jkflying: Sorry for the late reply. I have been on a holiday long away from my computer and Robocode.

The Kotlin fix should not ruin anything as the fix just allows the Kotlin standard library to be loaded by Robocode if the library is present inside the libs folder. Nothing else.

If 1.9.3.4 + CodeSize 1.2 works for RoboRumble, I propose I release Robocode as it is now as 1.9.3.5.

@bumfo: You have several pull requests waiting for Robocode. I will wait with these, if we freeze Robocode for 1.9.3.5 now.

**Comment by bumfo** [comment]
@flemming-n-larsen I propose pull request #19 be included in 1.9.3.5 as well, since it fixes a bug introduced in #14.

#17 may also be included, as it helps a cleaner output for rumble. 

Other bugs & pull requests are not essential for rumble IMO, so waiting for 1.9.3.6 is acceptable.

**Comment by flemming-n-larsen** [comment]
@bumfo: Okay. Let us concentrate about Rumble for 1.9.3.5, and then merge the remaining pull request etc. for 1.9.3.6. :-)
I make sense to include #19 and #17 for the Rumble.

**Comment by flemming-n-larsen** [comment]
I have built a the Robocode setup file for 1.9.3.5 was the changed for #17 and #19 and uploaded it here:
https://robocode.sourceforge.io/files/robocode-1.9.3.5-setup.jar

I will release this version if you guys think it is good enough for the rumble. :-)

**Comment by bumfo** [comment]
> I have built a the Robocode setup file for 1.9.3.5 was the changed for #17 and #19 and uploaded it here:
> https://robocode.sourceforge.io/files/robocode-1.9.3.5-setup.jar
> 
> I will release this version if you guys think it is good enough for the rumble. :-)

It seems that *rumble.sh and *rumble.command files are broken https://stackoverflow.com/questions/2920416/configure-bin-shm-bad-interpreter

This is due to line ending errors, however it seems that the files in git has correct line endings. May be some build script needs an update?

**Comment by flemming-n-larsen** [comment]
@bumfo Thanks for the notification. I believe you are right that something has changed regarding the build system. It might be a Maven plugin or something that has changed. I will look into that as well.

**Comment by flemming-n-larsen** [comment]
@bumfo The issue with ^M characters occurring in .sh and .command files have been fixed. The Robocode installer makes sure that any ^M characters are removed in those file types if they should occur. I believe the ^M characters are inserted when assembling the .jar archive for the setup file, which is system specific. So the installer fixes this when the files are installed on the Robocode folder.

**Comment by bumfo** [comment]
> @bumfo The issue with ^M characters occurring in .sh and .command files have been fixed. The Robocode installer makes sure that any ^M characters are removed in those file types if they should occur. I believe the ^M characters are inserted when assembling the .jar archive for the setup file, which is system specific. So the installer fixes this when the files are installed on the Robocode folder.
> 
> I uploaded a new version of 1.9.3.5 with this fix here:
> https://robocode.sourceforge.io/files/robocode-1.9.3.5-setup.jar

Great, this version now works as expected. Since other parts are already fully tested, I think we are ready for a release ;)

**Comment by flemming-n-larsen** [comment]
I am happy to hear that. The release will be done during this weekend. :-)

**Pull request merged**
